/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AmountEditor: typeof import('./src/components/AgGridRenderer/AmountEditor.vue')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATag: typeof import('ant-design-vue/es')['Tag']
    EnvironmentOutlined: typeof import('@ant-design/icons-vue')['EnvironmentOutlined']
    ErozeaMap: typeof import('./src/components/ErozeaMap/ErozeaMap.vue')['default']
    EyeOutlined: typeof import('@ant-design/icons-vue')['EyeOutlined']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ItemAgGridRenderer: typeof import('./src/components/AgGridRenderer/ItemAgGridRenderer.vue')['default']
    ItemArchorRenderer: typeof import('./src/components/AgGridRenderer/ItemArchorRenderer.vue')['default']
    LaptopOutlined: typeof import('@ant-design/icons-vue')['LaptopOutlined']
    NotificationOutlined: typeof import('@ant-design/icons-vue')['NotificationOutlined']
    QuestionCircleOutlined: typeof import('@ant-design/icons-vue')['QuestionCircleOutlined']
    QuestionOutlined: typeof import('@ant-design/icons-vue')['QuestionOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
