/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AmountEditor: typeof import('./src/components/AgGridRenderer/AmountEditor.vue')['default']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CloseCircleOutlined: typeof import('@ant-design/icons-vue')['CloseCircleOutlined']
    CurrencyRenderer: typeof import('./src/components/AgGridRenderer/CurrencyRenderer.vue')['default']
    ErozeaMap: typeof import('./src/components/ErozeaMap/ErozeaMap.vue')['default']
    EyeOutlined: typeof import('@ant-design/icons-vue')['EyeOutlined']
    ItemAgGridRenderer: typeof import('./src/components/AgGridRenderer/ItemAgGridRenderer.vue')['default']
    ItemArchorRenderer: typeof import('./src/components/AgGridRenderer/ItemArchorRenderer.vue')['default']
    ItemList: typeof import('./src/components/ItemList.vue')['default']
    MailOutlined: typeof import('@ant-design/icons-vue')['MailOutlined']
    ProjectMenu: typeof import('./src/components/ProjectMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
  }
}
